dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
before_install:
  - echo -e "Host 138.68.147.114\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_544cc9ef7876_key -iv $encrypted_544cc9ef7876_iv
    -in deploy-key.enc -out deploy-key -d
install:
  - npm install
script:
  - npm test

deploy:
    provider: script
    script: scripts/deploy.sh
    on:
        branch: master

notifications:
  email: false
